<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Todos.aspx.cs" Inherits="Todos.Todos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Todos</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>

            <asp:EntityDataSource
                ID="EntityDataSourceCategories" runat="server"
                ConnectionString="name=TodosDBEntities"
                DefaultContainerName="TodosDBEntities"
                EntitySetName="Categories"
                EnableFlattening="false"
                EnableDelete="true"
                EnableInsert="true"
                EnableUpdate="true">
            </asp:EntityDataSource>

            <asp:ListView ID="ListViewCategories" runat="server"
                DataSourceID="EntityDataSourceCategories"
                DataKeyNames="Id"
                ItemType="Todos.Category"
                OnItemInserted="ListViewCategory_ItemInserted">

                <LayoutTemplate>
                    <h3>Categories</h3>
                    <ul>
                        <asp:PlaceHolder runat="server" ID="ItemPlaceHolder" />
                    </ul>
                    <asp:Button ID="ButtonInsertCustomer"
                        Text="Insert" runat="server"
                        OnClick="ButtonInsertCategory_Click" />
                </LayoutTemplate>

                <ItemTemplate>
                    <asp:LinkButton Text='<%#: Eval("Name") %>' runat="server" ID="SelectLink" CommandName="Select" />
                    <asp:Button Text="Edit" runat="server" CommandName="Edit" />
                    <asp:Button Text="Delete" runat="server" CommandName="Delete" />
                    <asp:Button Text="Add Todo" runat="server" ID="ButtonAddTodo" OnClick="ButtonAddTodo_Click" />
                </ItemTemplate>

                <EditItemTemplate>
                    <li>
                        <asp:TextBox runat="server" ID="TextBoxCategoryName" Text='<%#: Bind("Name") %>' />
                        <asp:Button Text="Update" runat="server" CommandName="Update" />
                        <asp:Button Text="Cancel" runat="server" CommandName="Cancel" />
                    </li>
                </EditItemTemplate>

                <InsertItemTemplate>
                    <asp:TextBox runat="server" ID="TextBoxCategoryName" Text='<%#: Bind("Name") %>' />
                    <asp:Button ID="ButtonInsert" runat="server" CommandName="Insert" Text="Insert" />
                    <asp:Button ID="ButtonCancel" runat="server" CommandName="Cancel" Text="Clear" />
                </InsertItemTemplate>

                <ItemSeparatorTemplate>
                    <hr />
                </ItemSeparatorTemplate>

            </asp:ListView>

            <asp:PlaceHolder runat="server" ID="PlaceHolderCategoriesDetailsAdnAdd" />

            <asp:EntityDataSource
                ID="EntityDataSourceTodos" runat="server"
                ConnectionString="name=TodosDBEntities"
                DefaultContainerName="TodosDBEntities"
                EntitySetName="Todos"
                EnableFlattening="false"
                EnableDelete="true"
                EnableInsert="true"
                EnableUpdate="true"
                Where="it.CategoryId=@CategoryId">
                <WhereParameters>
                    <asp:ControlParameter Name="CategoryId" Type="Int32" ControlID="ListViewCategories" />
                </WhereParameters>
            </asp:EntityDataSource>

            <asp:GridView runat="server"
                ID="GridViewTodos"
                DataSourceID="EntityDataSourceTodos"
                AutoGenerateColumns="false"
                DataKeyNames="Id"
                AllowPaging="true"
                AllowSorting="true"
                AutoGenerateEditButton="true"
                AutoGenerateDeleteButton="true">
                <Columns>
                    <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                    <asp:BoundField DataField="Text" HeaderText="Text" SortExpression="Text" />
                </Columns>
            </asp:GridView>

            <asp:FormView runat="server" ID="FormViewAddTodo">
                <ItemTemplate>
                    <label>Title</label>
                    <asp:TextBox runat="server" ID="TextBoxTitle" />
                    <label>Text</label>
                    <asp:TextBox runat="server" ID="TextBoxText" />
                    <asp:Button Text="Save" ID="ButtonSave" OnClick="ButtonSave_Click" runat="server" />
                </ItemTemplate>
            </asp:FormView>

        </div>
    </form>
</body>
</html>
