// <auto-generated />
namespace Movies.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class Addedattributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedattributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201309251453314_Added attributes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
