//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateTimeUtils.Client.ServiceReferenceDateTimeUtil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceDateTimeUtil.IServiceDateTimeUtil")]
    public interface IServiceDateTimeUtil {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDateTimeUtil/GetDayOfWeek", ReplyAction="http://tempuri.org/IServiceDateTimeUtil/GetDayOfWeekResponse")]
        string GetDayOfWeek(System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDateTimeUtil/GetDayOfWeek", ReplyAction="http://tempuri.org/IServiceDateTimeUtil/GetDayOfWeekResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDateTimeUtilChannel : DateTimeUtils.Client.ServiceReferenceDateTimeUtil.IServiceDateTimeUtil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDateTimeUtilClient : System.ServiceModel.ClientBase<DateTimeUtils.Client.ServiceReferenceDateTimeUtil.IServiceDateTimeUtil>, DateTimeUtils.Client.ServiceReferenceDateTimeUtil.IServiceDateTimeUtil {
        
        public ServiceDateTimeUtilClient() {
        }
        
        public ServiceDateTimeUtilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDateTimeUtilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDateTimeUtilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDateTimeUtilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDayOfWeek(System.DateTime date) {
            return base.Channel.GetDayOfWeek(date);
        }
        
        public System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date) {
            return base.Channel.GetDayOfWeekAsync(date);
        }
    }
}
