//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibraryForStrings.Client.ServiceReferenceForStrings {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceForStrings.IServiceForStrings")]
    public interface IServiceForStrings {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceForStrings/GetData", ReplyAction="http://tempuri.org/IServiceForStrings/GetDataResponse")]
        int GetData(string firstString, string secondString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceForStrings/GetData", ReplyAction="http://tempuri.org/IServiceForStrings/GetDataResponse")]
        System.Threading.Tasks.Task<int> GetDataAsync(string firstString, string secondString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceForStringsChannel : WcfServiceLibraryForStrings.Client.ServiceReferenceForStrings.IServiceForStrings, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceForStringsClient : System.ServiceModel.ClientBase<WcfServiceLibraryForStrings.Client.ServiceReferenceForStrings.IServiceForStrings>, WcfServiceLibraryForStrings.Client.ServiceReferenceForStrings.IServiceForStrings {
        
        public ServiceForStringsClient() {
        }
        
        public ServiceForStringsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceForStringsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceForStringsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceForStringsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetData(string firstString, string secondString) {
            return base.Channel.GetData(firstString, secondString);
        }
        
        public System.Threading.Tasks.Task<int> GetDataAsync(string firstString, string secondString) {
            return base.Channel.GetDataAsync(firstString, secondString);
        }
    }
}
