// <auto-generated />
namespace Exam.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class ChangesinauthorIdtype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangesinauthorIdtype));
        
        string IMigrationMetadata.Id
        {
            get { return "201310071018174_Changes in authorId type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
