// the following (sample) data is generated by the Get() method of the Accounts controller.
[
	{
		"id":3,
		"iban":"BG00112233445566778811",
		"interestRate":6.12,
		"balance":150125.00,
		"accountType":{"Id":1,"Name":"Payment"},
		"transactionLogs":[]
	},

	{
		"id":1,
		"iban":"BG00112233445566778899",
		"interestRate":6.30,
		"balance":1500.00,
		"accountType":{"Id":1,"Name":"Payment"},
		"transactionLogs":
		[
			{"id":3,"amount":124.00,"timestamp":"1996-03-05T00:00:00","operation":{"Id":2,"Name":"Withdraw"}},
			{"id":4,"amount":55.00,"timestamp":"1994-02-05T00:00:00","operation":{"Id":1,"Name":"Deposit"}},
			{"id":5,"amount":153.00,"timestamp":"1994-03-04T00:00:00","operation":{"Id":2,"Name":"Withdraw"}}
		]
	},
		
	{
		"id":2,
		"iban":"BG00112233445566778888",
		"interestRate":7.14,
		"balance":1423.00,
		"accountType":{"Id":2,"Name":"Savings"},
		"transactionLogs":
		[
			{"id":2,"amount":100.00,"timestamp":"1994-03-05T00:00:00","operation":{"Id":1,"Name":"Deposit"}}
		]
	},
		
	{
		"id":4,
		"iban":"BG00112233585566778899",
		"interestRate":4.10,
		"balance":150.00,
		"accountType":{"Id":1,"Name":"Payment"},
		"transactionLogs":[]
	}
]