//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Authors = new HashSet<Author>();
            this.Rewiews = new HashSet<Rewiew>();
        }
    
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string ISBN { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string WebSite { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Rewiew> Rewiews { get; set; }
    }
}
