//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rewiew
    {
        public Rewiew()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int RewiewId { get; set; }
        public System.DateTime RewiewDate { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string RewiewText { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<Book> Books { get; set; }
    }
}
