//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikAcademy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkHoursLog
    {
        public int LogID { get; set; }
        public string CommandType { get; set; }
        public Nullable<int> OldWorkHoursID { get; set; }
        public Nullable<int> OldEmployeeID { get; set; }
        public Nullable<System.DateTime> OldWorkHoursDate { get; set; }
        public string OldTask { get; set; }
        public Nullable<System.TimeSpan> OldWorkHours { get; set; }
        public string OldComments { get; set; }
        public Nullable<int> NewWorkHoursID { get; set; }
        public Nullable<int> NewEmployeeID { get; set; }
        public Nullable<System.DateTime> NewWorkHoursDate { get; set; }
        public string NewTask { get; set; }
        public Nullable<System.TimeSpan> NewWorkHours { get; set; }
        public string NewComments { get; set; }
    }
}
